### ISSUE TITLE
TSP feature for BMN(Action Proposal)

### ISSUE THREAD

**Issue by LimGuenTaek** [HumamAlwassel/TSP#10]
Hi, Thanks a lot for sharing your code and features. It helped me a lot in my work.

Actually ... I tried to replicate **Action Proposal Generation using BMN framework with TSP feature.**

TSP framework returns Video feature : **(num_of_clips , 512)**

When I looked it up, BMN used features in the dimension **(100,400).**

I'm curious how you got the features to train BMN for action proposal generation.

I looked at issue and wondered if we just need to interpolate.

(num_of_clips , 512) -> 100 , 512

I would be so grateful if you could tell me the details.

Thanks for Your Paper , Work and Code

**Comment by HumamAlwassel** [comment]
Hi @LimGuenTaek,

Thanks for your interest in our work. 
To train BMN on TSP features, we use the same trick of interpolation I explained [here](https://github.com/HumamAlwassel/TSP/issues/9). The interpolation is mainly to avoid changing anything in the code of BMN and just swap the input features.

Cheers!
