### ISSUE TITLE
H5 files generated about GVF features

### ISSUE THREAD

**Issue by ZChengLong578** [HumamAlwassel/TSP#14]
Hi, @HumamAlwassel
Thanks for your excellent work and for sharing the code.
When I was training my dataset, I read your explanation on **GVF feature generation**. Do I need to combine  .pkl  files generated by the training set and valid set into .h5 files when I go to step 3?

**Comment by HumamAlwassel** [comment]
Hi @ZChengLong578,

Thanks for your interest in our work.

Yes, you should have both train and vali sets in one .h5 file. The training script expects only 1 single GVF file that has the max-pooled global features of each video in the train and val subsets.

Cheers!

**Comment by ZChengLong578** [comment]
Thank you for your answer! I still have some questions. In step 4, is it right to max-pooling of the features of each video, and then save the results of max-pooling in the new .h5 file in the original format? If so, how should the max-pooling parameters be set?

**Comment by HumamAlwassel** [comment]
I don't understand your question. 
Max-pooling has no parameters. For a given video features of size Tx512 (T is the number of clips), you need to apply the max operation on the T dimension such that you only get one vector per video of size 1×512.

**Comment by ZChengLong578** [comment]
Thank you for your answer, I have done this using the np.amax() function.

**Comment by ZChengLong578** [comment]
Thank you for your answer, I have done this using the np.amax() function.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HumamAlwassel/TSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 晚上10:53
***@***.***&gt;;
抄送:&nbsp;"唯@***@***.******@***.***&gt;;
主题:&nbsp;Re: [HumamAlwassel/TSP] H5 files generated about GVF features (Issue #14)





 
I don't understand your question.
 Max-pooling has no parameters. For a given video features of size Tx512 (T is the number of clips), you need to apply the max operation on the T dimension such that you only get one vector per video of size 1×512.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
