### ISSUE TITLE
question about pretrain-model

### ISSUE THREAD

**Issue by qt2139** [HumamAlwassel/TSP#19]
Hi, thank you for your excellent work. I have a problem with your model. It is extracted TSP Features in ActivityNet. When the objects present in my video are not in ActivityNet, the model fails to recognize. As an example, ActivityNet's animals are only dogs and horses, but when my video is a cat, I run into trouble. I'm guessing because the model hasn't seen cats, one of my solution is to use ImageNet-22k pretrained weights and then do extracted TSP Features in ActivityNet. I don't know if my thinking is right. If it is correct, could you please update your code about using ImageNet-22k pretrained weights? Thank you very much for your excellent work.

**Comment by HumamAlwassel** [comment]
Hi @qt2139 

Thanks for your interest in TSP.
The pretrained models we provide start from Kinetics TAC-pretraining before applying TSP on ActivityNet.
Pretraining on ImageNet is not the scope of this work. Keep in mind this is a video model targeted for temporal tasks. 

Cheers!
