### ISSUE TITLE
Confusion About Re-encoding

### ISSUE THREAD

**Issue by ASMIftekhar** [HumamAlwassel/TSP#2]
Hello,
Thanks for your wonderful work, I was planning to implement this on our custom dataset. However, you mentioned that we need to re-encode all the videos in a constant 30FPS. Is there any particular reason for that? What I understand changing the frame rate will change the time stamps for actions also, does that mean I need to change my annotations also?

**Comment by HumamAlwassel** [comment]
Hi @ASMIftekhar,

Thanks for your interest in our work. 

Some videos have variable frame rate encoding (i.e. the frame rate changes across the video). Thus, we re-encode all the videos to be at a constant frame rate (CFR) to make the dataset class easier to write. When dealing with CFR videos, we can know exactly how many frames are between any two timestamps, making the construction of the training dataset easier with the PyTorch video reader (take a look at our dataset class). The choice of 30fps is not of any particular importance as long as all videos are using CFR and not a variable frame rate. For simplicity, we chose to make all videos at 30fps when enforcing CFR.

Changing the frame rate should not change the annotations as the annotations should be in time (seconds) and not frame number. If your annotations are based on the frame number and not seconds, then you will also need to convert your annotations accordingly. My advice is to just use annotation in seconds from the first place to avoid any dependency on the frame rate. Hope this helps. 

Cheers
