### ISSUE TITLE
Accuracy don't increase

### ISSUE THREAD

**Issue by ZChengLong578** [HumamAlwassel/TSP#21]
Thank you for your reply! I used the above code to train my data set and found that the accuracy rate has not changed much and has remained around 3. Here is the output of the training:
![image](https://user-images.githubusercontent.com/86870600/173362988-130828bb-688f-4662-87ae-90172d87e932.png)
Do you know what caused it?

**Comment by HumamAlwassel** [comment]
Unfortunately, I cannot help you with this. It's hard to debug without access to the data. 

I'm gonna close this issue, but if you have anything further, please do *NOT* open a _new_ issue for every follow-up question. Please post your follow-up questions on the same issue even if it is closed. Opening new issues for follow-up questions unfortunately clutters the repo with too many issues that could just be in one thread. 

Thanks,
Humam
