### ISSUE TITLE
GVF features of different sizes

### ISSUE THREAD

**Issue by satish1901** [HumamAlwassel/TSP#4]
Hi Humam

So i generated gvf features for my dataset. Now when i use them for training, the dataloader throws an error of mismatch dimension when concatenation all features for a batch of different videos. 
The number of gvf [n X 512], where n is different for each video. how to i handle this ?

**Comment by HumamAlwassel** [comment]
Hi @satish1901,

You need to max-pool the local clip features [n×512] of one video to create a single GVF vector for that video. There should be only one vector of size 512 for each video.

Cheers!
