### ISSUE TITLE
ffmpeg version

### ISSUE THREAD

**Issue by yaru-zhang** [HumamAlwassel/TSP#6]
Hi, thanks for your work! Since version 4.2 ffmpeg comes back with the errors/warnings when I preprocessed a custom dataset into a standard version of fps30. I want to know which ffmpeg version will work fine to process the video.

`Stream #0: not enough frames to estimate rate; consider increasing probesize`

**Comment by HumamAlwassel** [comment]
Hi @yaru-zhang,

Thanks for your interest in our work. 
The error message seems to indicate an issue with the video itself and not the version of ffmpeg. Are the videos you are trying to convert have a specially large frame size?  If so, then the default value for `--probesize` might not be enough to estimate the effective frame rate. Consider adding the option `--probesize 50MB` to your ffmpeg call (adjust the value 50MB until ffmpeg stops complaining).

Read this post for more information about the issue: 
https://stackoverflow.com/questions/57903639/why-getting-and-how-to-fix-the-warning-error-on-ffmpeg-not-enough-frames-to-es

Hope this fixes the issue.
Cheers!
